language: python
python:
  - "3.6"

script:
  - echo "Hello, World!"

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    branch: pypi-deployment
#  on:
#    tags: true

notifications:
  email: false
